[versions]

# Minecraft
paper = "1.16.5-R0.1-SNAPSHOT"

# Adventure
kyori = "4.13.0"

[libraries]

# Minecraft
papermc = { module = "com.destroystokyo.paper:paper-api", version.ref = "paper" }
paperlib = { module = "io.papermc:paperlib", version = "1.0.8-SNAPSHOT" }

# Adventure
kyori = { module = "net.kyori:adventure-api", version.ref = "kyori" }
kyori-mm = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version = "2.11.2" }
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }
vault_api = { module = "com.github.MilkBowl:VaultAPI", version = "1.7" }

# Holograms
holographic_displays = { module = "me.filoghost.holographicdisplays:holographicdisplays-api", version = "3.0.1" }
decent_holograms = { module = "com.github.decentsoftware-eu:decentholograms", version = "2.8.1" }

cmi_api = { module = "com.Zrips.CMI:CMI-API", version = "9.3.1.5" }
cmi_lib = { module = "com.github.DoomsdaySociety:CMILib", version = "main-SNAPSHOT" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.3" }

# Item Plugins
itemsadder_api = { module = "com.github.LoneDev6:api-itemsadder", version = "3.0.0" }